version: '2'

services:

  storefront:
    build:
      context: ./saleor-storefront
      dockerfile: ./Dockerfile
    ports:
      - 3000:3000
    restart: unless-stopped
    volumes:
      - ./saleor-storefront/:/app:cached
      - /app/node_modules/
    command: npm start -- --host 0.0.0.0

  nginx:
    build:
      context: ./nginx
      dockerfile: ./Dockerfile.dev
    volumes:
      - static_volume:/home/app/static/
      - saleor-media:/app/media
    ports:
      - 80:80
    links:
      - storefront:storefront
    depends_on:
      - 
      - storefront
    networks:
      - saleor-backend-tier
volumes:
  saleor-media:
  static_volume:

networks:
  saleor-backend-tier:
    driver: bridge
